### ISSUE TITLE
Plot API Documentation

### ISSUE THREAD

**Issue by AgnesBaud** [motleystate/moonstone#18]
## Describe the bug

The [API Documentation for plot module](https://moonstone.readthedocs.io/en/latest/api_docs/plot.html) is not showing classes.

**Comment by AgnesBaud** [comment]
https://stackoverflow.com/questions/44989408/autodoc-directive-works-locally-but-not-on-readthedocs

**Comment by khillion** [comment]
As discussed, this is probably linked to the absence of `__init__.py` file in the `plot` directory
