### ISSUE TITLE
Randomly Select Reads

### ISSUE THREAD

**Issue by skennedy8** [motleystate/moonstone#27]
## Description
As a means of calculating diversity, the same number of reads should be used. This module will should take raw reads and return a subset of reads for all samples above a threshold.
This issue is related to #26 

### Related links
https://en.wikipedia.org/wiki/FASTQ_format

## Additional information
First iteration will be designed for paired-ends.
Later add single-read files, whole directories, and output of samples below the threshold.

**Comment by khillion** [comment]
Maybe it would be worth providing a independant module for fastq processing on moonstone even though it is not its primary purpose, what do you think?

**Comment by skennedy8** [comment]
For the moment I am planning to incorporate this under 'normalization.' It is a type of normalization that will be called when computing diversity. We can, of course, reposition it later if that makes sense.
